### ISSUE TITLE
K1M: [connectivity] 1000 to 2036 potential connection is missing from database

### ISSUE THREAD

**Issue by k1moradi** [Hippocampome-Org/php#357] opened 2017-08-29 19:56 UTC
1001 | DG Semilunar Granule (+)2311p | 2036 | CA3 Mossy Fiber-Associated (-)03330p-DG_0001

**Comment by drdiek** [comment] 2017-08-30 15:35
Keivan,

I am a little confused about this, since the potential connection shows up in the connectivity matrix and on the Semi-lunar granule cell neuron page and on the neuron page for MFA cells.

Sincerely,

Diek

**Comment by k1moradi** [comment] 2017-08-31 18:21
Diek,

Please try the following search query:

Connection:(Presynaptic:(Morphology:(Axons:DG:??1? OR Soma:DG:??1? OR Axons:CA3:??1?? OR Soma:CA3:??1??) AND Name:Granule AND Neurotransmitter:Excitatory), Postsynaptic:(Morphology:(Soma:CA3:??1?? OR Soma:CA3:?1???)))

For an unknown reason the mentioned connection is missing in the results.

Best,
Keivan

**Comment by drdiek** [comment] 2017-08-31 22:51
Keivan,

I found the connection in the results when I performed your search.

Sincerely,

Diek
![search_engine](https://user-images.githubusercontent.com/4380011/29948536-684c3d5a-8e7d-11e7-8d65-6ec6e15c72fa.jpg)

**Comment by k1moradi** [comment] 2017-09-01 17:47
No Diek it was 1000 -> 2036

sorry for my bad. You can check the API query also.

http://hippocampome.org/csv2db/search_engine_json.php?query_str=Connection:(Presynaptic:(Morphology:(Axons:DG:??1?%20OR%20Soma:DG:??1?%20OR%20Axons:CA3:??1??%20OR%20Soma:CA3:??1??)%20AND%20Name:Granule%20AND%20Neurotransmitter:Excitatory),%20Postsynaptic:(Morphology:(Soma:CA3:??1??%20OR%20Soma:CA3:?1???)))

**Comment by drdiek** [comment] 2017-09-01 21:07
Keivan,

According to the connectivity matrix the 1000 -> 2036 connection is refuted. However, when I click on the red X, I am taken to evidence that does not seem to have anything to do with either GCs or MFAs.

Christopher, are you tracking these missives, too? Can you spare a bit of time to look into this?

Sincerely,

Diek

**Comment by ChristopherRees** [comment] 2017-09-02 02:16
Hi Diek,

Yes, I am monitoring the missives and can look in to this later this weekend.  I’ll get back to you by Tuesday, at the latest.

Christopher

**Comment by k1moradi** [comment] 2017-10-26 21:27
Diek,

I am not sure what I can do to help? We need to fix the HCO data base. No? 
Refuted connection is still a potential connection and it should be in the data base. 
I am not convinced.

Sincerely,
Keivan

**Comment by drdiek** [comment] 2017-10-27 13:45
Hi all, 

I have tracked down the source of the problem with the “missing” potential connection.  I don’t know quite how it happened and I might ask Keivan to take the first step in fixing it, if he’s able and has time.  If not, I should have some time this weekend.

The bottom line is that I think the matrix is correct.  1000 -> 2036 is indeed a non-connection and should be marked by an X.  (Keivan, we had an email exchange about this non-connection on 3/17/16 where we modified the layers that were involved but agreed that the non-connection was correct.)  However, obviously, the evidence that is pointed to is incorrect.  The problem is that we seem to have TWO RefID 2000032s (sorry for any role I might have and probably did play in this).  When I look at Keivan’s Google sheets from which this matrix is generated (specifically, the sheet called 01_RefIDs), there are 2 references that are marked as RefID 2000032:
1.	Price et al., J Neurosci, 2005 (PMID 16033887), Figure 5.
2.	Szabadics and Soltesz, J Neurosci, 2009 (PMID 19339618), Figure 6.

The Price paper is showing up as evidence for this non-connection.  However, we want to point to the Szabadics paper.  So I think we need to create a new RefID for Szabadics, look at all uses of this RefID, and separate the two out properly to make sure the right one is invoked in every instance.  Keivan, can you help with this?  Once we get clean spreadsheets, I can re-generate the input needed David’s import scripts and send them on.

Thanks very much, and let me know if you have questions!
Christopher

**Comment by drdiek** [comment] 2020-01-17 16:40
The RefID for Szabadics and Soltesz was changed from 2000032 to 2000100, which has solved the problem.

**Closed** 2020-01-17 16:40 UTC
Labels: Development, Local, Production, Review, bug, csv2db
