### ISSUE TITLE
DWW: [neurites]: Propagate the errors (standard deviations) fully for the NxN matrices

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#547] opened 2020-07-02 19:35 UTC
@nmsutton Here is a Word document that outlines all of the steps necessary. Please let me know if you have any questions.

[How to propagate errors for NxN matrices.docx](https://github.com/Hippocampome-Org/php/files/4866274/How.to.propagate.errors.for.NxN.matrices.docx)

**Comment by drdiek** [comment] 2020-07-03 15:55
@nmsutton Hold off for a moment. I just realized I made a mistake in my directions. I will let you know when I have fixed it.

**Comment by drdiek** [comment] 2020-07-03 15:59
@nmsutton OK, I have fixed my instructions:

[How to propagate errors for NxN matrices.docx](https://github.com/Hippocampome-Org/php/files/4870502/How.to.propagate.errors.for.NxN.matrices.docx)

**Comment by nmsutton** [comment] 2020-07-09 01:19
@drdiek for the time being until I figure out how to implement the steps you described I uploaded new versions of the csv files for number of potential synapses, number of contacts, and synaptic probabilities that only contains the values in each of their respective matrices. This could help avoiding confusion for anyone downloading csv files and comparing them to the matrices. Thanks for providing your instructions, and my next work for this issue will be to implement the steps you described.

**Comment by nmsutton** [comment] 2020-07-09 01:40
@drdiek a question that come up for me is that, if the way the values are calculated is changed to include propagation of the errors, please tell me do formulas for that need to be put in the submitted manuscript to represent the updated formulas?

**Comment by drdiek** [comment] 2020-07-09 19:42
@nmsutton The errors on the values were not addressed in the manuscript. The errors only come into play on the website. The manuscript only concerns itself with the main formulas, so there is nothing to update in the manuscript. Thank you for asking, though.

**Comment by nmsutton** [comment] 2020-07-29 23:25
@drdiek On the NbyN parcel values summary page, only neuron pairs in the same parcel are reported on. This should be the same for your instructions such as 3.c:
`overlap_volume_mean_[parcel] = (axonal_volume_mean_[parcel] + dendritic_volume_mean_[parcel]) / 4` ? 
Generally, only values from pairs in the same parcel are reported on in the error propagation formulas, correct?

**Comment by drdiek** [comment] 2020-07-30 18:11
@nmsutton Correct.

**Comment by drdiek** [comment] 2020-07-31 14:18
@nmsutton I had a discussion with Giorgio yesterday about the calculations for the propagation of errors. It turns out that one of the manuscript’s reviewers asked about this very subject. Therefore, it has suddenly become a high priority item to be solved. Is there anything I can do to help in the process?

**Comment by nmsutton** [comment] 2020-07-31 15:57
@drdiek thanks for the offer to help. I have been working on this since completing my qual exam, and it is a somewhat complex problem. I am likely to have questions soon but not quite yet. One thing I can think of is for you to please continue to help with questions that I post on Github here, and I appreciate your assistance with that!

**Comment by nmsutton** [comment] 2020-08-01 23:59
@drdiek I think I may have completed this work but I would please like my work to be reviewed. I used an all-SQL approach to finding the requested values. I uploaded the code used to produce results in the csv2db_import repo ([link](https://github.com/Hippocampome-Org/csv2db_import/tree/master/csv2db/prop_error)). I documented each step of the approach on the dev-docs site ([link](https://hco-dev-docs.readthedocs.io/en/latest/synaptic_probabilities/propagate_errors.html)). I have attached 3 csv files ([results_files.zip](https://github.com/Hippocampome-Org/php/files/5011427/results_files.zip)) that are the total_nps, total_noc, and total_sp values, but they also exist as database tables that can be created by running the build_error_prop.sh script as explained on the dev-docs site. In addition to checking the final results, can you please try to use the build_error_prop.sh script to see if it appears to fully work your system?

**Comment by drdiek** [comment] 2020-08-03 15:46
@nmsutton In checking over your documentation, I apologize, but I notice that I made a few mistakes in a couple of my formulas.

For c.ii., there should be stdev's on the r.h.s of the equation, not means. Also, the division by 4 goes away, as it is a constant and has a stdev of zero.
c.ii. Calculate the overlap volume standard deviation: overlap_volume_stdev_[parcel] = sqrt(axonal_volume_stdev_[parcel]^2 + dendritic_volume_stdev_[parcel]^2).

For d.ii., the division by the volume_[parcel] goes away, as it is a constant and has a stdev of zero.
d.ii. Calculate the NPS standard deviation: NPS_stdev_[parcel] = NPS_mean_[parcel] * sqrt((axonal_length_stdev_[parcel] / axonal_length_mean_[parcel])^2 + (dendritic_length_stdev_[parcel] / dendritic_length_mean_[parcel])^2).

**Comment by nmsutton** [comment] 2020-08-04 06:00
@drdiek I have added your revisions and recreated the output. I also uploaded the new code to the csv2db_import repo and added some notes about conditions to help get the scripts working in MySQL to the dev docs (and updated them with your new formulas). I have attached the new results data [results_2.zip](https://github.com/Hippocampome-Org/php/files/5020327/results_2.zip) to this post (but the data can be recreated by running the uploaded SQL code as well). Please, when you get a chance, review the work.

**Comment by drdiek** [comment] 2020-08-04 17:52
@nmsutton I do not understand how to run the build_error_prop.sh script. How do I define which database I am attempting to modify, and how do I enter the database password?

I need to check some of the intermediate values, because my own results for errors do not match your for the case of 1001 to 1006. Do I skip running build_error_prop.sh and just execute the individual commands?

**Comment by nmsutton** [comment] 2020-08-04 20:38
@drdiek in the build_error_prop.sh script it uses the mysql_user, mysql_password, and mysql_db_name found in database_save.sh in the base csv2db_import directory. This is a file that you create based on the example_database_save.sh file. You could execute the individual commands, but it may be faster to run the build_error_prop script. Please tell me what you find after you look into it, and if you are still having issues running the build_error_prop script after creating database_save.sh.

**Comment by drdiek** [comment] 2020-08-04 22:54
@nmsutton I receive an error when I try to run the script:

$ ./build_error_prop.sh
Creating constants table
ERROR 1045 (28000): Access denied for user '-pmysql_user=root'@'localhost' (using password: NO)

Among other things, it does not appear to be detecting my password.

**Comment by nmsutton** [comment] 2020-08-04 23:28
@drdiek I have attached ([build_error_prop_mod.zip](https://github.com/Hippocampome-Org/php/files/5025289/build_error_prop_mod.zip)) a version where you can simply type your user, pass, and db at the top of the script. Please see if that works if you try it.

**Comment by drdiek** [comment] 2020-08-04 23:38
@nmsutton Do I need to put the username, etc. in quotes?

**Comment by nmsutton** [comment] 2020-08-04 23:40
@drdiek on my system (ubuntu 20.04) you should not use quotes for any of the variables including username.

**Comment by drdiek** [comment] 2020-08-05 00:02
@nmsutton It appears that order_of_pairs.sql is expecting the database name to be hippocsv2db, which is not the name of my local database, so the scripting broke. I edited the line, but now constants.sql causes an error because the table already exists. So, every time the scripting breaks, I will apparently have to manually delete all of the created tables.

**Comment by drdiek** [comment] 2020-08-05 00:06
@nmsutton Now I am really confused. I cannot find the SynproErrPropConstants table in my database in order to delete it. Therefore, I do not understand where constants.sql is looking that it finds this table already existing.

**Comment by nmsutton** [comment] 2020-08-05 00:17
@drdiek if you are using MySQL Workbench, SynproErrPropConstants is listed under a group called "views", not regular tables. The approach I used creates temporary tables (views). Try looking for a separate group of tables that is for views.

**Comment by drdiek** [comment] 2020-08-05 01:01
@nmsutton The file number_of_parcels.sql is looking for a table entitled report_lengths_convex_hulls, which does not appear to exist.

**Comment by nmsutton** [comment] 2020-08-05 01:15
@drdiek I think unfortunately you are using an outdated version of the code. Please d/l the latest version from csv2db_import. I corrected the issue you are describing yesterday.

**Comment by drdiek** [comment] 2020-08-05 11:45
@nmsutton I have discovered a discrepancy between my hand-calculated values and yours. For 1001 to 1006, the overlap_volume_std differs: my value is 1267177.641 and your value is 1310.8005187670624. The factors that go into the calculation of this value match between you and me: axonal_convex_hull_std = 604497.565 and dendritic_convex_hull_std = 1113697.3850000002. Your final value is off by 3 orders of magnitude for some reason, although the formula in volume_of_overlap.sql appears to be correct, so I am unsure what is going wrong.

**Comment by nmsutton** [comment] 2020-08-05 15:36
@drdiek I have figured out the issue there. In MySQL syntax I should have used POW(..., 2) instead of ... ^ 2. I have updated the code. In that instance, I originally forgot to do that. Please d/l the latest csv2db_import code for the corrected version. I have re-run the software and generated new results which I have attached ([results_3.zip](https://github.com/Hippocampome-Org/php/files/5029392/results_3.zip)).

**Comment by drdiek** [comment] 2020-08-05 16:52
@nmsutton In total_nps.sql, you are not following the instructions in line 4.a.ii. In the file you are simply taking the standard deviation of the means, when you need to be calculating the square root of the squares of the individual standard deviations. The same goes for total_noc.sql (4.b.ii.) and total_cp.sql (4.c.ii.).

**Comment by drdiek** [comment] 2020-08-05 17:29
@nmsutton In thinking about this, I now realize how tricky this is going to be to execute properly, because the number of parcels is variable for each connection. I am not sure how you will be able to program this. Perhaps you could save the squares of the individual standard deviations as an intermediate step, which might make summing the squares easier?

**Comment by drdiek** [comment] 2020-08-05 17:31
@nmsutton The square of the standard deviation is the variance, in case you needed a convenient abbreviation for the number.

**Comment by nmsutton** [comment] 2020-08-05 17:35
@drdiek thanks for the suggestions and I think I found a way to get the correct formula for this. Please d/l the latest code to look at it. I have attached ([results_4.zip](https://github.com/Hippocampome-Org/php/files/5030181/results_4.zip)) new results.

**Comment by drdiek** [comment] 2020-08-05 17:47
@nmsutton OK, I do not understand how it works, but it seems to work now. Both you and I are generating the same values for the total means and standard deviations, at least for the case of 1001 to 1006, which I consider to be good enough confirmation.

**Comment by nmsutton** [comment] 2020-08-05 18:00
@drdiek thanks, I think the key to how it works is the "group by" condition. That organizes the results by neuron pairs, and the formula automatically adjusts for the variable number of parcels that can be included based on the grouping. Please tell me, now that we have the updated values, where should those be applied to the matrix data? Just to make sure I am applying the results to the correct places, what values on the site should be updated with the new results?

**Comment by drdiek** [comment] 2020-08-05 18:43
@nmsutton I would report the means and standard deviations in hover-over windows for all three of the NxN matrices. Can you also create hover-over windows for the intermediate tables, or is that not possible because the values are stored in views and not tables?

**Comment by nmsutton** [comment] 2020-08-05 19:36
@drdiek ok, so in the NbyN matricies the values listed in each cell should contain the mean values from the new calculations. Also, hover overs should be added and have the mean and stdev. I would assume the parcel breakdown page needs to be updated with the new values as well, correct? I can convert the views into permanent tables. The values in the connection probability tool are based on the files in the /data/ directory. Do those /data/ files need to be updated?

**Comment by drdiek** [comment] 2020-08-05 19:43
@nmsutton Yes, please update the main matrices and the parcel breakdown pages. The files in the /data/ directory are all updated to the latest values.

**Comment by nmsutton** [comment] 2020-08-05 20:00
@drdiek ok sure, just to confirm, you are saying that you updated the /data/ files and I don't need to, right?

**Comment by drdiek** [comment] 2020-08-05 22:21
@nmsutton As far as I know, the /data/ files are up to date and do not need further updating.

**Comment by nmsutton** [comment] 2020-08-06 18:51
@drdiek please help me with a question that came up. Some calculations, such as NPS_mean_total rely on convex hull volume data, yet that data is missing for a portion of neuron pairs. Specifically, 
`SELECT distinct unique_id, neurite, filtered_total_length, convexhull
FROM neurite_quantified
WHERE filtered_total_length!='' AND convexhull='';`
returns: `471` rows.
It seems to me that the code I created will only output results for neuron pairs that are not missing data. Given that missing data can cause the error propagation calculations not to be able to be completed, what values should be reported in those cases? Should no values be reported, or should values without the new error propagation formulas be reported?

**Comment by drdiek** [comment] 2020-08-06 21:46
@nmsutton This is an intriguing situation you have highlighted. However, I would not expect the number of potential synapses (NPS) to be affected, as they are only a function of the axonal and dendritic lengths. On the other hand, the number of contacts (NC) would be affected, as they are depended on the lengths and the convex hull volumes. Furthermore, we will only be able to calculate the connection probabilities (CP) for pairs for which we have NC values. If you are unable to calculate a value for NC or CP, then I would not report anything.

**Comment by nmsutton** [comment] 2020-08-07 03:30
@drdiek Thanks for the advice about not reporting a value if data is missing. I found that in the earlier query with convexhull='' query it mainly affecting neurites with "All" (which aren't used in prop of error calcs), e.g., "Sub:All:D", but it also affects 24 entries with parcel specified (which are used in the calcs) according to this query:
`SELECT DISTINCT
    unique_id, neurite, filtered_total_length, convexhull
FROM
    neurite_quantified
WHERE
    filtered_total_length != ''
        AND convexhull = ''
        AND neurite not like '%:all:%';`
In total I have observed that each of the end total value results for CP, NC, and NPS have 11 less neuron pairs than the original values (1970-1959=11). That is only 0.5% of all original neuron pairs and I suspect missing data needed for the new calculations is the reason behind it. That percent doesn't seem like much of a difference. I also found other missing data it appears when I investigated the 11 pairs. One thing I found was that the number_of_contacts table reports for the id pairs (6006,6033) and (6006,6086) values are reported for EC layer VI. However, the neurite_quantified table is missing any lengths or convex hull values for id 6006 and that layer `(SELECT * FROM neurite_quantified
WHERE unique_id=6006
AND neurite like 'EC:VI:%';).` Therefore, the prop of errors I assume wouldn't be able to compute values for that and indeed that appears to be the case. While it is fine to account for the small fraction of less pairs due to missing data, I want to go through the code and make sure it handles missing data in an effective way (e.g., no value result if insufficient data). This however may need to wait until after I complete my presentation for Monday.

**Comment by drdiek** [comment] 2020-08-07 15:10
@nmsutton It is fine to wait until after your presentation. 

I have done some investigation into 6006. It turns out there are typos in the number_of_contacts.csv file. The VI in the file is supposed to be IV for both pairs.

That brings us down to 9 pairs left to debug. I expect there might be similar explanations for these remaining 9.

**Comment by nmsutton** [comment] 2020-08-07 16:27
@drdiek thanks for resolving that. The other missing pairs are (1041,1035), (1041,1036), (4055,4068), (4055,4091), (6078,6017), (6078,6018), (6078,6082), and (6082,6025). One missing one is (6040,6006) but that one is probably effected by the 6006 typo. That leaves just those 8. I think just walking through the sql commands with each of them will reveal at what point they stop producing results. If you have extra time you could try doing that before I get a chance to try, but of course, there is no obligation for you to do so; I'll work on it and post what I find the soonest I have time for that.

**Comment by nmsutton** [comment] 2020-08-07 16:47
@drdiek btw, please d/l the latest code if you run it; I made an update yesterday.

**Comment by drdiek** [comment] 2020-08-07 16:51
@nmsutton I have taken care of (6040,6006), (1041,1035), (1041,1036), (4055,4068), (4055,4091), (6078,6017), (6078,6018), (6078,6082), and (6082,6025). They were all typos of one sort or another.

**Comment by nmsutton** [comment] 2020-08-07 17:38
@drdiek impressive work resolving those so quickly! Please tell me when the typos have been corrected and I will rebuild the database with the new data. Hopefully, that resolves the last of the things needed to be sorted out. I will still later want to run some tests to see how the code handles the 24 convexhull = '' entries, but if it handles those fine, then there are no issues with that.

**Comment by drdiek** [comment] 2020-08-07 17:45
@nmsutton All of the typos have been corrected already, so you are free to rebuild the database.

**Comment by nmsutton** [comment] 2020-08-08 18:51
@drdiek I rebuilt the database and recreated the tables but still 11 pairs are different than the original tables. I'm sure that your correction of typos will help with any issues that could arise due to that. I will further investigate the convexhull = '' entries and those pairs to see what is going on with them. If you have extra time, you could try running those particular pairs with the scripts to see what occurs, if you want to. I will work on it more after my presentation on Mon in any case.

**Comment by nmsutton** [comment] 2020-08-09 04:51
@drdiek actually sorry about that last comment. I realized that I imported the wrong version of the database after I rebuilt it. After I imported the correct one, all NbyN tables with error propagation are matching the number of pairs included when values are generated without error propagation. Hopefully you didn't spend time on trying to debug that, and sorry about my mixup. Thanks a lot for correcting the typos, and it seems that may have fully brought the new calculations to the point of providing the results we are looking for. I will also upload the latest rebuilt database to the cng server within the next 30min.

**Comment by nmsutton** [comment] 2020-08-11 19:39
@drdiek I found unfortunately some more what appears to be errors in the neurite_quantified table.  When I run this query `SELECT DISTINCT
    unique_id, subregion, neurite, filtered_total_length, convexhull
FROM
    neurite_quantified
WHERE
    filtered_total_length != ''
        AND convexhull = ''
        AND neurite NOT LIKE '%:all:%';`, it can be seen that many subregions listed do not match the ones listed in the neurite descriptions. Can you please take a look at this and help make sure the data is entered correctly? This could influence results from the new calculations if subregion data was misentered I assume. From what I understand my scripts use the neurite column to extract the subregion, layer, and neurite info, so that is the column I am most interested in being correct.

**Comment by nmsutton** [comment] 2020-08-11 20:57
@drdiek I also found something similar with this different query: `SELECT DISTINCT
    unique_id,
    subregion,
    neurite,
    filtered_total_length,
    convexhull
FROM
    neurite_quantified
WHERE
    filtered_total_length = ''
        AND convexhull != ''
        AND neurite NOT LIKE '%:all:%';`

**Comment by nmsutton** [comment] 2020-08-11 21:24
@drdiek perhaps these entries are not errors because the difference only perhaps appear in axons. The subregion is perhaps based on the dendrite location and axons can be in different subregions than the neurons' dendrite.

**Comment by nmsutton** [comment] 2020-08-11 21:41
@drdiek a question that comes up is, for such axons, should I use the subregion listed in the "subregion" column or the "neurite" column to identify the subregion for the axons? The only place the parcel is listed along with the filtered_total_length and convexhull is the neurite column, and because we need the parcel for our calculations, I would assume that means to keep using the data the same way I already am, and ignore the subregion column. Otherwise it would conflict with the subregion listed for the parcel.

**Comment by drdiek** [comment] 2020-08-12 11:51
@nmsutton Some neurons are projection neurons, so their axons invade subregions other than where their cell body is, which means the subregion listed in the "subregion" column will differ from that in the "neurite" column. Therefore, you should use the subregion listed in the "neurite" column.

I am unable to dump a copy of the hippodevome database on the cng server. I am getting the following error:
mysqldump: Couldn't execute 'show create table `SynproConnProb`': SHOW VIEW command denied to user 'hdb'@'localhost' for table 'SynproConnProb' (1142)
Any idea what this might mean?

**Comment by nmsutton** [comment] 2020-08-12 15:47
@drdiek thanks for the explanation. I have an idea ot what that means. Each command (e.g., select) is s privilege assigned to each user (e.g., hdb, the public user). I should be able to grant the "view" privilege to the hdb user, since the db may now contain views. I'll look a little about security with that but I assume it is fine. Currently the original way the database was designed on the server only assigned the "select" privilege to the hdb user.

**Comment by nmsutton** [comment] 2020-08-12 16:33
@drdiek I added the privilege with `GRANT SHOW VIEW ON *.* TO 'hdb'@'localhost';`. Please try the db import again.

**Comment by drdiek** [comment] 2020-08-12 18:01
@nmsutton That did the trick.

**Comment by drdiek** [comment] 2020-08-12 19:50
@nmsutton When I tried to import the dumped database onto my computer, I received the following error:

ERROR 1449 (HY000) at line 2413: The user specified as a definer ('nsutton2'@'localhost') does not exist

It seems to be a rather odd error, in that it did not flag earlier appearances of your username as definer.

**Comment by nmsutton** [comment] 2020-08-12 20:04
@drdiek this appears to be an issue specific to views. I found this information "This commonly occurs when exporting views/triggers/procedures from one database or server to another as the user that created that object no longer exists." ([source](https://stackoverflow.com/questions/10169960/mysql-error-1449-the-user-specified-as-a-definer-does-not-exist)). Eventually the views will be deleted once I convert the relevant ones to perminant tables, and therefore they will not be in the db and cause issues.In the meantime, before then, you could if you want create a user nsutton2 with whatever password you want on your personal computer db and it will fix the issue I assume.

**Comment by drdiek** [comment] 2020-08-12 20:13
@nmsutton Yes, creating the new user worked.

**Comment by nmsutton** [comment] 2020-08-13 00:45
@drdiek I have created 6 permanent tables through adding code for that in csv2db_import's model.py and map.py. I rebuilt the database and rebuilt the json and parcel breakdown page queries. Now the values from the error propagation calculations are on the 3 NbyN matrices, and all the values have hover-overs with mean and std. The values link to the parcel breakdown page and that page displays the values by parcel of the new calculations. All intermediate temporary tables including views have been removed from the database, since the permanent tables were created. The updates are live on the phpdev server. Please review this work and see if it is complete.

**Comment by nmsutton** [comment] 2020-08-13 00:49
@drdiek on a related note, the J of Neuroscience review specifically asked for "would it be possible to provide error estimates for the reported connection probabilities, for example from the variabilities of the underlying morphological data? Such error estimates could help clarify some of the discrepancies mentioned above." Since from what I understand, the error propagation calculations integrate error values into the final value calculations, but we do not report what the error values are, is this sufficient to fulfill the reviewer's request to "provide error estimates"?

**Comment by drdiek** [comment] 2020-08-13 14:28
@nmsutton There are some problems with significant digits in the hover over windows. For the Number of Potential Synapses, for DG Semilunar Granule (1001) to DG Basket (1035), there are too many digits in the reported standard deviation. For the Number of Contacts matrix, the windows are showing more digits than the matrix values display. For the Synaptic Probabilities matrix, for DG Mossy (1002) to DG Hilar Ectopic Granule (1041), the number of digits for the standard deviation do not match the number of digits for the mean.

I think we will be able to satisfy the reviewer through a combination of the error values in the matrices and a description of how they were derived in the manuscript.

**Comment by nmsutton** [comment] 2020-08-13 17:03
@drdiek I think that I have now fixed the formatting issues you described. Please review the matrices and see if it looks completed. Also, just to confirm, when you wrote 'error values in the matrices', you mean the values reported in the matrices currently are sufficient without additional reporting, correct?

**Comment by drdiek** [comment] 2020-08-13 17:12
@nmsutton I meant the currently reported values plus the hover-over windows will be sufficient.

**Comment by drdiek** [comment] 2020-08-14 18:18
@nmsutton One last item. Please add the newly computed errors to the downloadable csv files for the three NxN matrices.

**Comment by nmsutton** [comment] 2020-08-15 16:59
@drdiek I have uploaded the new csv downloadable files to phpdev. I also added their sql scripts to the php repo. Please review the work to see if it has been completed.

**Comment by drdiek** [comment] 2020-08-17 13:59
@nmsutton It looks as though you have accomplished all that I have set before you, but there is still one thing that is troubling me. Some of the errors end up being zero because there is only one example of an axon and only one example of a dendrite. It feels to me as if we need to have an error in those situations, too, so I will give some thought to this. One avenue is that we determine the length of axons and dendrites by counting pixels. Counts have associated errors with them, which might be used in these certain situations.

**Comment by drdiek** [comment] 2020-08-18 02:01
@nmsutton Can you add code so that all of the errors that are equal to zero display "N/A" instead?

**Comment by nmsutton** [comment] 2020-08-18 15:32
@drdiek sure, and am I correct in understanding that when the stdev is 0, that is when the errors are equal to 0?

**Comment by drdiek** [comment] 2020-08-18 17:35
@nmsutton Yes.

**Comment by drdiek** [comment] 2020-08-19 23:39
@nmsutton There are some problems with the calculations for EC neuron types, in particular for the Number of Potential Synapses. When a neuron type name begins with MEC, for either the presynaptic or postsynaptic neuron, then the parcel volume to be used comes from row 2 of either EC-Table-1.csv or EC-Table-2.csv. When a neuron type name begins with LEC, for either the presynaptic or postsynaptic neuron, then the parcel volume to be used comes from row 1 of either EC-Table-1.csv or EC-Table-2.csv. When both the presynaptic and the postsynaptic neurons names start with just EC, then the parcel volume to be used comes from row 3 of either EC-Table-1.csv or EC-Table-2.csv. I thought for sure you had accommodated these rules in your code already, but I found some discrepancies between your values and Carolina's values for some EC neuron types, and I tracked the fault down to the MEC / LEC / EC factor.

**Comment by drdiek** [comment] 2020-08-25 12:55
@nmsutton It is difficult for me to evaluate the results in this form. Could you please generate the .csv files that are downloadable from the website? I need to be able to easily judge whether the neuron types are excitatory or inhibitory.

**Comment by drdiek** [comment] 2020-08-25 16:17
@nmsutton While I have your attention, in the downloadable .csv files, can you please change the (+)'s and (-)'s to (e)'s and (i)'s? We switched our nomenclature some years ago.

**Comment by nmsutton** [comment] 2020-08-25 19:43
@drdiek I have attached ([example_csv_dls.zip](https://github.com/Hippocampome-Org/php/files/5125937/example_csv_dls.zip)) example csv d/l files. I also updated the names to have (e) and (i). Please review the files and see if the calculations match your own.

**Comment by drdiek** [comment] 2020-08-25 22:41
@nmsutton It does not look as though the values have changed from previously. They are still very far off of what Carolina has generated.

**Comment by nmsutton** [comment] 2020-08-25 23:39
@drdiek my mistake, sorry. I exported from the old tables by accident. Please review these ([csv_dl_results_2.zip](https://github.com/Hippocampome-Org/php/files/5126788/csv_dl_results_2.zip)) to see if they match your calculations.

**Comment by drdiek** [comment] 2020-08-25 23:59
@nmsutton They still seem to be the old values.

**Comment by nmsutton** [comment] 2020-08-26 00:52
@drdiek according to the files I have, there were 391 pairs with changed values. I have created a spreadsheet showing them ([changes_summary.zip](https://github.com/Hippocampome-Org/php/files/5126913/changes_summary.zip)). Perhaps there was confusion about when you asked for csv files downloadable from the website, I included them in this attached file: [csv_dl_results_2.zip](https://github.com/Hippocampome-Org/php/files/5126788/csv_dl_results_2.zip). I did not actually upload them to the website. If I upload the csv file then they would not match the matrix or parcel specific values page, because I would need to rebuild those based on the new values. I considered it better to just attach the csv files in Github, then if you say they are correct, I will upload and rebuild the matrix content. One other thing is that in the process of integrating the mec,lec,and ec layer info, I updated some subregion descriptions to better match the /data/ files, and therefore a few pairs outside of the EC region had values updated. The large majority of updates were all in the EC subregion. Please tell me, does this clarify what the changes are? If there are any values that still do not appear correct, can you please provide some specific examples of what those are so that I can investigate them?

**Comment by drdiek** [comment] 2020-08-26 08:35
@nmsutton Here are a couple of the values I have been spot checking that have not changed:

MEC LII-III Pyramidal-Multiform (e)233111	6008	EC LI-II Multipolar-Pyramidal (e)231000	6094	0.002216816	0.010485522
MEC LII-III Pyramidal-Multiform (e)233111	6008	EC LI-II Pyramidal-Fan (e)331000p	6005	0.000619998	0.001110158

**Comment by drdiek** [comment] 2020-08-26 14:57
@nmsutton Those were cp values that I listed.

**Comment by drdiek** [comment] 2020-08-26 18:33
@nmsutton (6008, 6094) 0.007000972, and (6008, 6005) 0.001958031.

**Comment by nmsutton** [comment] 2020-08-26 19:25
@drdiek thanks. I found there was a surprising MySQL arithmatic synatax bug when calculating the smallest volume_[parcel] that I fixed. New results now match the example correct values you provided. I also found that noc, nps, and cp all have different numbers of pairs with changed values, and therefore I made seperate results summaries for each. I have included the new results with summaries in this attached file: [results_3.zip](https://github.com/Hippocampome-Org/php/files/5132409/results_3.zip). Please review the results and tell me if this looks completed.

**Comment by drdiek** [comment] 2020-08-26 20:47
@nmsutton The values were updated in the results_3.zip files, but not in the files from the other link.

**Comment by nmsutton** [comment] 2020-08-26 21:35
@drdiek I was using the old tables again, here are the results (same as results3.zip) including summaries and 'N/A' replacements: [results_3_with_na.zip](https://github.com/Hippocampome-Org/php/files/5132877/results3_with_na.zip).

**Comment by drdiek** [comment] 2020-08-26 22:42
@nmsutton These are still the old values.

**Comment by nmsutton** [comment] 2020-08-26 23:33
@drdiek ok, I don't know what happened last time, but this time I went through and made sure they are all the newest values. Here are files of the newest results (matching results_3.zip) with summaries and 'N/A's: [results_3_ver2.zip](https://github.com/Hippocampome-Org/php/files/5133152/results_3_ver2.zip). I also made the threshold on the summaries to only report changes if they are within 10 decimal places, so that should show only more noticeable changes.

**Comment by drdiek** [comment] 2020-08-27 00:14
@nmsutton This looks more promising. I will let you know how my full comparison with Carolina's data pans out.

**Comment by drdiek** [comment] 2020-08-27 14:19
@nmsutton Overall the match is pretty good. For EC I-I and I-E pairings, the values match. However, for EC E-I and E-E pairings, your values are larger than Carolina's for some reason. At this point, I am more inclined to believe your values than hers, but I am going to do some hand checking to determine where the discrepancies are exactly.

**Comment by drdiek** [comment] 2020-08-31 16:32
@nmsutton After some discussion with Giorgio and Carolina, it has been decided that whenever there is a hybrid match-up of parcels (i.e. EC to MEC, EC to LEC, MEC to EC, or LEC to EC), we should be using the whole EC parcel volume and not the MEC/LEC parcel volumes. We only use the MEC volume for MEC to MEC pairings, and we only use the LEC volume for LEC to LEC pairings. Sorry for the confusion.

**Comment by nmsutton** [comment] 2020-09-02 15:47
@drdiek ok, to confirm, MEC to LEC pairings use the EC volume and not MEC or LEC volume, correct?

**Comment by drdiek** [comment] 2020-09-02 16:52
@nmsutton There are no MEC to LEC or LEC to MEC pairings, as they do not overlap at all.

**Comment by nmsutton** [comment] 2020-09-02 18:02
@drdiek I have created new results with the updated rules ([results_4.zip](https://github.com/Hippocampome-Org/php/files/5163988/results_4.zip)). Please review them and see if this work is completed.

**Comment by drdiek** [comment] 2020-09-02 18:56
@nmsutton I am getting a different value from you for the connection probability (cp) in the pairing of MEC LII Stellate (e)331111p [6003] to EC LI-II Multipolar-Pyramidal (e)231000 [6094]. Your value is 0.013950858, and my value is 0.015495247. We get identical values for MEC LII-III Pyramidal-Multiform (e)233111 [6008] to EC LI-II Multipolar-Pyramidal (e)231000 [6094].

**Comment by nmsutton** [comment] 2020-09-02 19:42
@drdiek thanks, I checked the volume values with that pair and they do not appear incorrect with my new code. Specifically, where selected_volume is the one used for the formula, 
`source_id, target_id, subregion_source, subregion_target, parcel, volume_source, volume_target, selected_volume`
`'6003', '6094', 'MEC', 'EC', 'I', '2576770345.000000', '7918472146.000000', '7918472146.000000'`
`'6003', '6094', 'MEC', 'EC', 'II', '3628376490.000000', '11458847642.000000', '11458847642.000000'`
Please tell me, for (6003,6094) can you provide each your intermediate values, e.g., each value in step 3f, so that I can see where in the calculation processes the answers are diverging?

**Comment by nmsutton** [comment] 2020-09-02 19:55
@drdiek Here are my intermediate values for NPS_mean_[parcel], the first formula in the series of equations that uses the new updated volume value:
NPS_mean_[parcel] = c * axonal_length_mean_[parcel] * dendritic_length_mean_[parcel] / volume_[parcel]
NPS_mean_(6003,6094,I) = 0.018399487666087004 =  4.958615216027455 * 3488.4399999999996 *   8422.78 / 7918472146.000000
NPS_mean_(6003,6094,II) = 0.01608915077085663 = 4.958615216027455 * 5946.543333333334 *  6252.433333333334 / 11458847642.000000

**Comment by nmsutton** [comment] 2020-09-02 20:37
@drdiek 
NC_mean_[parcel] = (1 / parcel_count) + (constant * axonal_length_mean * dendritic_length_mean) / overlap_volume_mean
NC_mean_(6003,6094,I) =  2.54485680977643 = (1/2)+(4.958615216027455 * 3488.4399999999996 * 8422.78)/71249893.82533333
NC_mean_(6003,6094,II) = 2.3939374791682067 = (1/2)+(4.958615216027455 * 5946.543333333334 * 6252.433333333334)/97343829.66716668

CP_mean_[parcel] = NPS_mean/NC_mean
CP_mean_(6003,6094,I) = 0.00723006795329417 = 0.018399487666087004/2.54485680977643
CP_mean_(6003,6094,II) =  0.006720789874782752 = 0.01608915077085663/2.3939374791682067

CP_mean_total = CP_mean_[parcel1] + CP_mean_[parcel2] + …
CP_mean_(6003,6094) = 0.013950858 = 0.00723006795329417 + 0.006720789874782752

**Comment by drdiek** [comment] 2020-09-02 20:47
@nmsutton 
NPS_mean_(6003,6094,I) = 0.018399488 = 4.958615217 * 3488.44 * 8422.78 / 7918472146
NPS_mean_(6003,6094,II) = 0.019255663 = 4.958615217 * 7116.89 * 6252.43 / 11458847642

The difference appears to lie in the axonal_length_mean_[parcel] for II. The two values I am averaging are 13622.95 and 610.82, which I obtained from the Evidence page for this pairing.

**Comment by nmsutton** [comment] 2020-09-02 21:32
@drdiek you appear to be missing the 3rd axonal length in your calculations, 3605.86. Your calculation is (13622.95+610.82)/2=7116.885 but the correct one is (13622.95+610.82+3605.86)/3=5946.5433. That 3rd length is found by the query below and also visible on the phpdev site in the evidence page for 6003 layer II axon.
`SELECT distinct filtered_total_length FROM hippocsv2db.neurite_quantified
WHERE unique_ID = 6003
AND neurite='EC:II:A'
AND filtered_total_length != '';`

**Comment by drdiek** [comment] 2020-09-02 22:59
@nmsutton Thanks. There were only two axonal entries for Layer I, so I assumed the same was true for Layer II. I just didn't scroll down far enough on the page. Everything matches now.

**Comment by nmsutton** [comment] 2020-09-13 20:29
@drdiek I have updated all NxN materials on phpdev with the propagation of errors results. This includes the main matrix pages, parcel breakdown pages, and csv downloads. Please check if this Github issue is completed.

**Comment by drdiek** [comment] 2020-09-14 20:33
@nmsutton Can you please double check the values for 6003-XXXX for CP_mean? The values for other pairings seem okay, but for these, the values in the .CSV downloadable file do not match the quotient of NPS_mean/NC_mean, if you look at the values from those two .CSV files.

**Comment by nmsutton** [comment] 2020-09-14 21:26
@drdiek I think something that may help clarify this is that the formula for CP_mean is
CP_mean_total = CP_mean_[parcel1] + CP_mean_[parcel2]
Therefore, CP_mean will not be NPS_mean/NC_mean from the NPS and NC csv files. It is instead calculated as CP_mean = NPS_mean_parcel1/NC_mean_parcel1 + NPS_mean_parcel2/NC_mean_parcel2... The NPS and NOC csv files do not show parcel-specific means, only pair-specific means, so that parcel information needed for calculating CP_mean can be not shown in the NPS+NOC csv files.
For example, pair (6003, 6094):
source_id, target_id, subregion, parcel, NPS_mean, NC_mean, CP_mean
6003, 6094, MEC, I, 0.018399487666087004, 2.54485680977643, 0.00723006795329417
6003, 6094, MEC, II, 0.01608915077085663, 2.3939374791682067, 0.006720789874782752
CP_mean_(6003,6094) = 0.01395 = 0.00723 + 0.00672
It does not equal 0.03449/4.93879 = 0.00698 based on NPS_csv_mean_(6003,6094)/NOC_csv_mean_(6003,6094)
This is because there are 2 parcels in the calculation. The csv files accurately report NPS, NOC, and CP mean values in this example of (6003,6094). Please share, do you have a pair that you can provide that does not have the correct values?

**Comment by drdiek** [comment] 2020-09-14 22:10
@nmsutton Thank you. Your explanation about the parcels makes sense.

**Comment by nmsutton** [comment] 2020-09-18 01:41
@drdiek you're welcome. Just to try to keep track of this, if you find that the values are acceptable, please evaluate if this issue is completed.

**Closed** 2020-09-18 13:30 UTC
Labels: defect
