### ISSUE TITLE
GAA: [FP]: On all Firing Pattern Evidence pages, the Protocol information is all listed as 'unknown'

### ISSUE THREAD

**Issue by drdiek** [Hippocampome-Org/php#516] opened 2020-04-02 18:06 UTC
From Giorgio: "Today while meeting with Jeffrey I noticed that all the evidence supporting firing patterns (open from the corresponding matrix) says:
Protocol: species unknown | protocol unknown | temperature unknown
I guess one of the tables is not properly linked in the DB?"

**Comment by drdiek** [comment] 2020-04-08 16:57
@nmsutton I have been delving into this and have discovered that the necessary data is missing from our current version of the database. In the Fragment table, there should be 10,476 entries according to an old version of the database that I found dated 20171203. The current version of the Fragment table only has 10,451 entries. In addition, of the entries that do exist in the current version of the Fragment table, some data is missing from the page_location column. Entries for electrophysiology should look something like "p2403 | Fig5D, r | p | 35 | b," but none of the current entries have data in this format. The data gets into this format in the file csv2db/lib/epdata_string_field.py, where the variable "protocol" gets merged into the variable "page_location." In summary, somehow, something is broken in the import in a major way.

**Comment by nmsutton** [comment] 2020-04-08 17:27
@drdiek Thanks for looking into this. From what I am aware of none of any work I have done has affected epdata_string_field.py but I could try to trace the code deeper to find out more. Do you have any backups of the csv2db code and csv files from 20171203 that could be looked at for differences?

**Comment by drdiek** [comment] 2020-05-07 16:11
@nmsutton I am mailing you a link to the oldest version of the code and csv files that I have, as the compressed files is too big to link here.

**Comment by drdiek** [comment] 2020-05-07 18:47
@nmsutton I just copied the old version of epdata_string_field.py over, and, according to GitHub, there have been no changes to the file since way back in 2017.

In copying over an older version of epdata.csv, I notice that there are a lot of changes. For ephys data, we contrived a 14-digit reference ID number for the various pieces of ephys data. In the more current version of epdata.csv, these reference ID had been compressed down to a handful of significant digits and the rest being omitted due to the number being compressed into scientific notation. I am wondering if this could somehow be related to the missing database entries, but I just do not know how.

**Comment by drdiek** [comment] 2020-05-14 19:22
@nmsutton After talking with Giorgio, he suggested that as a stop-gap measure I simply replace the fragment table with an older version that still contains all of the necessary data. I have now done this for all of the current versions of the databases on the server. It seems to have temporarily fixed our problem. If you ever need to update the dev database, you can use this table to temporarily "fix" this problem again: [hippocsv2db_201712031821_fragment.sql.zip](https://github.com/Hippocampome-Org/php/files/4630427/hippocsv2db_201712031821_fragment.sql.zip)

**Comment by nmsutton** [comment] 2020-05-14 19:48
@drdiek thanks for the work on this. I have now created branches in the php and csv2db-import for synpro_submission_v1 that freeze in place the version we have of the code for when we have submitted it, now that Carolina has submitted it (really great news!). I find it can be important to back that up in case questions or changes come up.

From what I understand you don't want the old version of fragment to be on the main files collection, it is only a temporary fix for the current issue. I'll assume development work can continue with the current version on the repos unless you tell me otherwise.

**Comment by drdiek** [comment] 2020-05-15 10:50
@nmsutton That is correct. This is just a kludge. We need to determine why the information is no longer getting into the database from the spreadsheets.

**Comment by nmsutton** [comment] 2020-05-23 05:12
@drdiek can you please provide the older version of epdata.csv that you mentioned? It appears that is the source of protocol information and if some content from the old version is needed instead of the new one I would like to compare them.

**Comment by drdiek** [comment] 2020-05-23 12:06
@nmsutton Here it is: [epdata.csv.zip](https://github.com/Hippocampome-Org/php/files/4671722/epdata.csv.zip)

**Comment by nmsutton** [comment] 2020-05-23 15:22
@drdiek I ran csv2db with the epdata file you provided and it did not produce the protocol information error. It also produces a fragment table with 10,476 entries instead of 10,451 entries. I find that the source of the issue is very likely to be that file. Please tell me, do you think there can be a way to merge the data in that file with the current one to correct the issue? Is there new data in the latest file that can not be removed?

**Comment by nmsutton** [comment] 2020-05-28 16:41
@drdiek hi, I just want to check in about this. Please tell me, do you think you may want more time for further investigations with the options/requirements between the old vs. new epdata.csv file?

**Comment by drdiek** [comment] 2020-05-28 18:49
@nmsutton Sorry, yes, I need a bit more time to investigate and resolve the file differences.

**Comment by drdiek** [comment] 2020-05-28 19:22
@nmsutton OK, I think I may have tracked the difference between the two versions of the file, or at least the only difference I can discern. For historical reasons, we ended up crafting 14-digit reference IDs to identify Alexander's ephys data values. The 2017 version of the the epdata.csv file maintains all 14 of those digits, whereas the 2020 version of the file has rounded off to only 6 digits or so. The php code is likely having trouble locating data because of these roundings; otherwise, there is no difference between the two versions of the file. My conclusion is to simply proceed with the 2017 version of the file.

**Comment by nmsutton** [comment] 2020-05-28 23:31
@drdiek I have now uploaded the '17 epdata to github and ran csv2db with it. I uploaded all db output to sftp://129.174.10.81/ (cng2 server) in /home/nsutton2/temp/db_052820/. I am referring to you, in case there is anything special nedded, to update all hco db versions with that, since I have never done that before (I only update dev server). Do you have a script that automatically updates all db versions on the cng1 server?

Thanks,

Nate

**Comment by drdiek** [comment] 2020-05-29 01:27
@nmsutton No, I have been doing it by hand at the moment, since I haven't taken the time to try to write a script. Perhaps I will take the time to try. The trickiest part is the user table, as there are several flags that need to be set for the various versions of the database.

**Comment by nmsutton** [comment] 2020-06-08 18:01
@drdiek Thanks for the help uploading the new content to all site versions. I can see the properties are displayed correctly on the site now. Please review this and if this looks completed please close this issue.

**Closed** 2020-06-12 12:16 UTC
Labels: bug
